import type { BadgeDefinition } from "../types";

export const ATTENDANCE_BADGES: BadgeDefinition[] = [
  {
    id: "attend_first",
    badgeKey: "attend_first",
    emoji: "👋",
    title: "첫방문",
    description: "앱에 첫 출석했어요",
    tier: "tutorial",
    xp: 5,
    category: "attendance",
    progressTarget: 1,
    check: (_recs, _badges, streak) => ({
      unlocked: streak >= 1,
      progressCurrent: Math.min(streak, 1),
      progressTarget: 1,
    }),
  },
  {
    id: "attend_3",
    badgeKey: "attend_3",
    emoji: "📅",
    title: "3일 연속 출석",
    description: "3일 연속으로 앱에 방문했어요",
    tier: "easy",
    xp: 10,
    category: "attendance",
    progressTarget: 3,
    check: (_recs, _badges, streak) => ({
      unlocked: streak >= 3,
      progressCurrent: Math.min(streak, 3),
      progressTarget: 3,
    }),
  },
  {
    id: "attend_7",
    badgeKey: "attend_7",
    emoji: "🗓️",
    title: "7일 연속 출석",
    description: "7일 연속으로 앱에 방문했어요",
    tier: "medium",
    xp: 25,
    category: "attendance",
    progressTarget: 7,
    check: (_recs, _badges, streak) => ({
      unlocked: streak >= 7,
      progressCurrent: Math.min(streak, 7),
      progressTarget: 7,
    }),
  },
  {
    id: "attend_14",
    badgeKey: "attend_14",
    emoji: "🏆",
    title: "14일 연속 출석",
    description: "14일 연속으로 앱에 방문했어요",
    tier: "hard",
    xp: 50,
    category: "attendance",
    progressTarget: 14,
    check: (_recs, _badges, streak) => ({
      unlocked: streak >= 14,
      progressCurrent: Math.min(streak, 14),
      progressTarget: 14,
    }),
  },
  {
    id: "attend_30",
    badgeKey: "attend_30",
    emoji: "📆",
    title: "30일 연속 출석",
    description: "30일 연속으로 앱에 방문했어요",
    tier: "hard",
    xp: 50,
    category: "attendance",
    progressTarget: 30,
    check: (_recs, _badges, streak) => ({
      unlocked: streak >= 30,
      progressCurrent: Math.min(streak, 30),
      progressTarget: 30,
    }),
  },
  {
    id: "attend_100",
    badgeKey: "attend_100",
    emoji: "📆",
    title: "100일 연속 출석",
    description: "100일 연속으로 앱에 방문했어요",
    tier: "epic",
    xp: 100,
    category: "attendance",
    progressTarget: 100,
    check: (_recs, _badges, streak) => ({
      unlocked: streak >= 100,
      progressCurrent: Math.min(streak, 100),
      progressTarget: 100,
    }),
  },
  {
    id: "attend_total_30",
    badgeKey: "attend_total_30",
    emoji: "🗓️",
    title: "30일 누적 출석",
    description: "총 30일 동안 앱에 방문했어요",
    tier: "medium",
    xp: 25,
    category: "attendance",
    progressTarget: 30,
    check: (_recs, _badges, _streak, _myTeam, _installDate, totalDays) => ({
      unlocked: (totalDays ?? 0) >= 30,
      progressCurrent: Math.min(totalDays ?? 0, 30),
      progressTarget: 30,
    }),
  },
  {
    id: "attend_total_100",
    badgeKey: "attend_total_100",
    emoji: "🗓️",
    title: "100일 누적 출석",
    description: "총 100일 동안 앱에 방문했어요",
    tier: "hard",
    xp: 50,
    category: "attendance",
    progressTarget: 100,
    check: (_recs, _badges, _streak, _myTeam, _installDate, totalDays) => ({
      unlocked: (totalDays ?? 0) >= 100,
      progressCurrent: Math.min(totalDays ?? 0, 100),
      progressTarget: 100,
    }),
  },
  {
    id: "attend_total_365",
    badgeKey: "attend_total_365",
    emoji: "🎊",
    title: "365일 누적 출석",
    description: "총 365일 동안 앱에 방문했어요 — 1년을 함께했네요",
    tier: "epic",
    xp: 100,
    category: "attendance",
    progressTarget: 365,
    check: (_recs, _badges, _streak, _myTeam, _installDate, totalDays) => ({
      unlocked: (totalDays ?? 0) >= 365,
      progressCurrent: Math.min(totalDays ?? 0, 365),
      progressTarget: 365,
    }),
  },
];
