import type { TeamColor } from "./types";

export const TEAM_COLORS: Record<string, TeamColor> = {
  doosan: {
    id: "doosan",
    name: "두산 베어스",
    shortName: "두산",
    primary: "#131230",
    secondary: "#FFFFFF",
    tertiary: "#C4161C",
  },
  lg: {
    id: "lg",
    name: "LG 트윈스",
    shortName: "LG",
    primary: "#C30452",
    secondary: "#000000",
    tertiary: "#FFFFFF",
  },
  kt: {
    id: "kt",
    name: "KT 위즈",
    shortName: "KT",
    primary: "#000000",
    secondary: "#EB1F25",
    tertiary: "#FFFFFF",
  },
  ssg: {
    id: "ssg",
    name: "SSG 랜더스",
    shortName: "SSG",
    primary: "#CE0E2D",
    secondary: "#F0A832",
    tertiary: "#1D1D1B",
  },
  nc: {
    id: "nc",
    name: "NC 다이노스",
    shortName: "NC",
    primary: "#1D467D",
    secondary: "#C6973F",
    tertiary: "#FFFFFF",
  },
  samsung: {
    id: "samsung",
    name: "삼성 라이온즈",
    shortName: "삼성",
    primary: "#074CA1",
    secondary: "#FFFFFF",
    tertiary: "#C4C4C4",
  },
  lotte: {
    id: "lotte",
    name: "롯데 자이언츠",
    shortName: "롯데",
    primary: "#002B5C",
    secondary: "#D00F31",
    tertiary: "#FFFFFF",
  },
  hanwha: {
    id: "hanwha",
    name: "한화 이글스",
    shortName: "한화",
    primary: "#FF6600",
    secondary: "#000000",
    tertiary: "#FFFFFF",
  },
  kia: {
    id: "kia",
    name: "KIA 타이거즈",
    shortName: "KIA",
    primary: "#EA0029",
    secondary: "#000000",
    tertiary: "#FFFFFF",
  },
  kiwoom: {
    id: "kiwoom",
    name: "키움 히어로즈",
    shortName: "키움",
    primary: "#820024",
    secondary: "#000000",
    tertiary: "#FFFFFF",
  },
};

export const TEAM_LIST = Object.values(TEAM_COLORS);
