// Auto-generated character asset map
// Basic emotions: default, neutral, joyful, sad, angry, furious, shocked

export const LOCAL_CHARACTERS: Record<string, number> = {
  "doosan_default": require("../assets/team-characters/doosan_default.png"),
  "hanwha_default": require("../assets/team-characters/hanwha_default.png"),
  "kia_default": require("../assets/team-characters/kia_default.png"),
  "kiwoom_default": require("../assets/team-characters/kiwoom_default.png"),
  "kt_default": require("../assets/team-characters/kt_default.png"),
  "lg_default": require("../assets/team-characters/lg_default.png"),
  "lotte_default": require("../assets/team-characters/lotte_default.png"),
  "nc_default": require("../assets/team-characters/nc_default.png"),
  "samsung_default": require("../assets/team-characters/samsung_default.png"),
  "ssg_default": require("../assets/team-characters/ssg_default.png"),
  "doosan_neutral": require("../assets/team-characters/doosan_neutral.png"),
  "hanwha_neutral": require("../assets/team-characters/hanwha_neutral.png"),
  "kia_neutral": require("../assets/team-characters/kia_neutral.png"),
  "kiwoom_neutral": require("../assets/team-characters/kiwoom_neutral.png"),
  "kt_neutral": require("../assets/team-characters/kt_neutral.png"),
  "lg_neutral": require("../assets/team-characters/lg_neutral.png"),
  "lotte_neutral": require("../assets/team-characters/lotte_neutral.png"),
  "nc_neutral": require("../assets/team-characters/nc_neutral.png"),
  "samsung_neutral": require("../assets/team-characters/samsung_neutral.png"),
  "ssg_neutral": require("../assets/team-characters/ssg_neutral.png"),
  "doosan_joyful": require("../assets/team-characters/doosan_joyful.png"),
  "hanwha_joyful": require("../assets/team-characters/hanwha_joyful.png"),
  "kia_joyful": require("../assets/team-characters/kia_joyful.png"),
  "kiwoom_joyful": require("../assets/team-characters/kiwoom_joyful.png"),
  "kt_joyful": require("../assets/team-characters/kt_joyful.png"),
  "lg_joyful": require("../assets/team-characters/lg_joyful.png"),
  "lotte_joyful": require("../assets/team-characters/lotte_joyful.png"),
  "nc_joyful": require("../assets/team-characters/nc_joyful.png"),
  "samsung_joyful": require("../assets/team-characters/samsung_joyful.png"),
  "ssg_joyful": require("../assets/team-characters/ssg_joyful.png"),
  "doosan_sad": require("../assets/team-characters/doosan_sad.png"),
  "hanwha_sad": require("../assets/team-characters/hanwha_sad.png"),
  "kia_sad": require("../assets/team-characters/kia_sad.png"),
  "kiwoom_sad": require("../assets/team-characters/kiwoom_sad.png"),
  "kt_sad": require("../assets/team-characters/kt_sad.png"),
  "lg_sad": require("../assets/team-characters/lg_sad.png"),
  "lotte_sad": require("../assets/team-characters/lotte_sad.png"),
  "nc_sad": require("../assets/team-characters/nc_sad.png"),
  "samsung_sad": require("../assets/team-characters/samsung_sad.png"),
  "ssg_sad": require("../assets/team-characters/ssg_sad.png"),
  "doosan_angry": require("../assets/team-characters/doosan_angry.png"),
  "hanwha_angry": require("../assets/team-characters/hanwha_angry.png"),
  "kia_angry": require("../assets/team-characters/kia_angry.png"),
  "kiwoom_angry": require("../assets/team-characters/kiwoom_angry.png"),
  "kt_angry": require("../assets/team-characters/kt_angry.png"),
  "lg_angry": require("../assets/team-characters/lg_angry.png"),
  "lotte_angry": require("../assets/team-characters/lotte_angry.png"),
  "nc_angry": require("../assets/team-characters/nc_angry.png"),
  "samsung_angry": require("../assets/team-characters/samsung_angry.png"),
  "ssg_angry": require("../assets/team-characters/ssg_angry.png"),
  "doosan_furious": require("../assets/team-characters/doosan_furious.png"),
  "hanwha_furious": require("../assets/team-characters/hanwha_furious.png"),
  "kia_furious": require("../assets/team-characters/kia_furious.png"),
  "kiwoom_furious": require("../assets/team-characters/kiwoom_furious.png"),
  "kt_furious": require("../assets/team-characters/kt_furious.png"),
  "lg_furious": require("../assets/team-characters/lg_furious.png"),
  "lotte_furious": require("../assets/team-characters/lotte_furious.png"),
  "nc_furious": require("../assets/team-characters/nc_furious.png"),
  "samsung_furious": require("../assets/team-characters/samsung_furious.png"),
  "ssg_furious": require("../assets/team-characters/ssg_furious.png"),
  "doosan_shocked": require("../assets/team-characters/doosan_shocked.png"),
  "hanwha_shocked": require("../assets/team-characters/hanwha_shocked.png"),
  "kia_shocked": require("../assets/team-characters/kia_shocked.png"),
  "kiwoom_shocked": require("../assets/team-characters/kiwoom_shocked.png"),
  "kt_shocked": require("../assets/team-characters/kt_shocked.png"),
  "lg_shocked": require("../assets/team-characters/lg_shocked.png"),
  "lotte_shocked": require("../assets/team-characters/lotte_shocked.png"),
  "nc_shocked": require("../assets/team-characters/nc_shocked.png"),
  "samsung_shocked": require("../assets/team-characters/samsung_shocked.png"),
  "ssg_shocked": require("../assets/team-characters/ssg_shocked.png"),
};

export const BASIC_EMOTIONS = new Set(['default', 'neutral', 'joyful', 'sad', 'angry', 'furious', 'shocked']);
