export const ALL_EMOTIONS = new Set([
  "default",
  "determined",
  "sad",
  "joyful",
  "neutral",
  "angry",
  "furious",
  "shocked",
  "annoyed",
  "crying",
  "curious",
  "depressed",
  "flustered",
  "mocking",
  "sleepy",
  "tongue",
  "in_love",
  "extream_shock",
  "devastated",
  "hot_summer",
  "karen",
  "out",
  "praying",
  "rain_cancellation",
  "resigned_disgust",
  "thumbs_up",
  "provocative",
]);

export const LOCAL_CHARACTERS: Record<string, number> = {
  "doosan_default": require("../assets/team-characters/doosan_default.webp"),
  "doosan_determined": require("../assets/team-characters/doosan_determined.webp"),
  "doosan_sad": require("../assets/team-characters/doosan_sad.webp"),
  "doosan_joyful": require("../assets/team-characters/doosan_joyful.webp"),
  "doosan_neutral": require("../assets/team-characters/doosan_neutral.webp"),
  "doosan_angry": require("../assets/team-characters/doosan_angry.webp"),
  "doosan_furious": require("../assets/team-characters/doosan_furious.webp"),
  "doosan_shocked": require("../assets/team-characters/doosan_shocked.webp"),
  "doosan_annoyed": require("../assets/team-characters/doosan_annoyed.webp"),
  "doosan_crying": require("../assets/team-characters/doosan_crying.webp"),
  "doosan_curious": require("../assets/team-characters/doosan_curious.webp"),
  "doosan_depressed": require("../assets/team-characters/doosan_depressed.webp"),
  "doosan_flustered": require("../assets/team-characters/doosan_flustered.webp"),
  "doosan_mocking": require("../assets/team-characters/doosan_mocking.webp"),
  "doosan_sleepy": require("../assets/team-characters/doosan_sleepy.webp"),
  "doosan_tongue": require("../assets/team-characters/doosan_tongue.webp"),
  "doosan_in_love": require("../assets/team-characters/doosan_in_love.webp"),
  "doosan_extream_shock": require("../assets/team-characters/doosan_extream_shock.webp"),
  "doosan_devastated": require("../assets/team-characters/doosan_devastated.webp"),
  "doosan_hot_summer": require("../assets/team-characters/doosan_hot_summer.webp"),
  "doosan_karen": require("../assets/team-characters/doosan_karen.webp"),
  "doosan_out": require("../assets/team-characters/doosan_out.webp"),
  "doosan_praying": require("../assets/team-characters/doosan_praying.webp"),
  "doosan_rain_cancellation": require("../assets/team-characters/doosan_rain_cancellation.webp"),
  "doosan_resigned_disgust": require("../assets/team-characters/doosan_resigned_disgust.webp"),
  "doosan_thumbs_up": require("../assets/team-characters/doosan_thumbs_up.webp"),
  "doosan_provocative": require("../assets/team-characters/doosan_provocative.webp"),
  "hanwha_default": require("../assets/team-characters/hanwha_default.webp"),
  "hanwha_determined": require("../assets/team-characters/hanwha_determined.webp"),
  "hanwha_sad": require("../assets/team-characters/hanwha_sad.webp"),
  "hanwha_joyful": require("../assets/team-characters/hanwha_joyful.webp"),
  "hanwha_neutral": require("../assets/team-characters/hanwha_neutral.webp"),
  "hanwha_angry": require("../assets/team-characters/hanwha_angry.webp"),
  "hanwha_furious": require("../assets/team-characters/hanwha_furious.webp"),
  "hanwha_shocked": require("../assets/team-characters/hanwha_shocked.webp"),
  "hanwha_annoyed": require("../assets/team-characters/hanwha_annoyed.webp"),
  "hanwha_crying": require("../assets/team-characters/hanwha_crying.webp"),
  "hanwha_curious": require("../assets/team-characters/hanwha_curious.webp"),
  "hanwha_depressed": require("../assets/team-characters/hanwha_depressed.webp"),
  "hanwha_flustered": require("../assets/team-characters/hanwha_flustered.webp"),
  "hanwha_mocking": require("../assets/team-characters/hanwha_mocking.webp"),
  "hanwha_sleepy": require("../assets/team-characters/hanwha_sleepy.webp"),
  "hanwha_tongue": require("../assets/team-characters/hanwha_tongue.webp"),
  "hanwha_in_love": require("../assets/team-characters/hanwha_in_love.webp"),
  "hanwha_extream_shock": require("../assets/team-characters/hanwha_extream_shock.webp"),
  "hanwha_devastated": require("../assets/team-characters/hanwha_devastated.webp"),
  "hanwha_hot_summer": require("../assets/team-characters/hanwha_hot_summer.webp"),
  "hanwha_karen": require("../assets/team-characters/hanwha_karen.webp"),
  "hanwha_out": require("../assets/team-characters/hanwha_out.webp"),
  "hanwha_praying": require("../assets/team-characters/hanwha_praying.webp"),
  "hanwha_rain_cancellation": require("../assets/team-characters/hanwha_rain_cancellation.webp"),
  "hanwha_resigned_disgust": require("../assets/team-characters/hanwha_resigned_disgust.webp"),
  "hanwha_thumbs_up": require("../assets/team-characters/hanwha_thumbs_up.webp"),
  "hanwha_provocative": require("../assets/team-characters/hanwha_provocative.webp"),
  "kia_default": require("../assets/team-characters/kia_default.webp"),
  "kia_determined": require("../assets/team-characters/kia_determined.webp"),
  "kia_sad": require("../assets/team-characters/kia_sad.webp"),
  "kia_joyful": require("../assets/team-characters/kia_joyful.webp"),
  "kia_neutral": require("../assets/team-characters/kia_neutral.webp"),
  "kia_angry": require("../assets/team-characters/kia_angry.webp"),
  "kia_furious": require("../assets/team-characters/kia_furious.webp"),
  "kia_shocked": require("../assets/team-characters/kia_shocked.webp"),
  "kia_annoyed": require("../assets/team-characters/kia_annoyed.webp"),
  "kia_crying": require("../assets/team-characters/kia_crying.webp"),
  "kia_curious": require("../assets/team-characters/kia_curious.webp"),
  "kia_depressed": require("../assets/team-characters/kia_depressed.webp"),
  "kia_flustered": require("../assets/team-characters/kia_flustered.webp"),
  "kia_mocking": require("../assets/team-characters/kia_mocking.webp"),
  "kia_sleepy": require("../assets/team-characters/kia_sleepy.webp"),
  "kia_tongue": require("../assets/team-characters/kia_tongue.webp"),
  "kia_in_love": require("../assets/team-characters/kia_in_love.webp"),
  "kia_extream_shock": require("../assets/team-characters/kia_extream_shock.webp"),
  "kia_devastated": require("../assets/team-characters/kia_devastated.webp"),
  "kia_hot_summer": require("../assets/team-characters/kia_hot_summer.webp"),
  "kia_karen": require("../assets/team-characters/kia_karen.webp"),
  "kia_out": require("../assets/team-characters/kia_out.webp"),
  "kia_praying": require("../assets/team-characters/kia_praying.webp"),
  "kia_rain_cancellation": require("../assets/team-characters/kia_rain_cancellation.webp"),
  "kia_resigned_disgust": require("../assets/team-characters/kia_resigned_disgust.webp"),
  "kia_thumbs_up": require("../assets/team-characters/kia_thumbs_up.webp"),
  "kia_provocative": require("../assets/team-characters/kia_provocative.webp"),
  "kiwoom_default": require("../assets/team-characters/kiwoom_default.webp"),
  "kiwoom_determined": require("../assets/team-characters/kiwoom_determined.webp"),
  "kiwoom_sad": require("../assets/team-characters/kiwoom_sad.webp"),
  "kiwoom_joyful": require("../assets/team-characters/kiwoom_joyful.webp"),
  "kiwoom_neutral": require("../assets/team-characters/kiwoom_neutral.webp"),
  "kiwoom_angry": require("../assets/team-characters/kiwoom_angry.webp"),
  "kiwoom_furious": require("../assets/team-characters/kiwoom_furious.webp"),
  "kiwoom_shocked": require("../assets/team-characters/kiwoom_shocked.webp"),
  "kiwoom_annoyed": require("../assets/team-characters/kiwoom_annoyed.webp"),
  "kiwoom_crying": require("../assets/team-characters/kiwoom_crying.webp"),
  "kiwoom_curious": require("../assets/team-characters/kiwoom_curious.webp"),
  "kiwoom_depressed": require("../assets/team-characters/kiwoom_depressed.webp"),
  "kiwoom_flustered": require("../assets/team-characters/kiwoom_flustered.webp"),
  "kiwoom_mocking": require("../assets/team-characters/kiwoom_mocking.webp"),
  "kiwoom_sleepy": require("../assets/team-characters/kiwoom_sleepy.webp"),
  "kiwoom_tongue": require("../assets/team-characters/kiwoom_tongue.webp"),
  "kiwoom_in_love": require("../assets/team-characters/kiwoom_in_love.webp"),
  "kiwoom_extream_shock": require("../assets/team-characters/kiwoom_extream_shock.webp"),
  "kiwoom_devastated": require("../assets/team-characters/kiwoom_devastated.webp"),
  "kiwoom_hot_summer": require("../assets/team-characters/kiwoom_hot_summer.webp"),
  "kiwoom_karen": require("../assets/team-characters/kiwoom_karen.webp"),
  "kiwoom_out": require("../assets/team-characters/kiwoom_out.webp"),
  "kiwoom_praying": require("../assets/team-characters/kiwoom_praying.webp"),
  "kiwoom_rain_cancellation": require("../assets/team-characters/kiwoom_rain_cancellation.webp"),
  "kiwoom_resigned_disgust": require("../assets/team-characters/kiwoom_resigned_disgust.webp"),
  "kiwoom_thumbs_up": require("../assets/team-characters/kiwoom_thumbs_up.webp"),
  "kiwoom_provocative": require("../assets/team-characters/kiwoom_provocative.webp"),
  "kt_default": require("../assets/team-characters/kt_default.webp"),
  "kt_determined": require("../assets/team-characters/kt_determined.webp"),
  "kt_sad": require("../assets/team-characters/kt_sad.webp"),
  "kt_joyful": require("../assets/team-characters/kt_joyful.webp"),
  "kt_neutral": require("../assets/team-characters/kt_neutral.webp"),
  "kt_angry": require("../assets/team-characters/kt_angry.webp"),
  "kt_furious": require("../assets/team-characters/kt_furious.webp"),
  "kt_shocked": require("../assets/team-characters/kt_shocked.webp"),
  "kt_annoyed": require("../assets/team-characters/kt_annoyed.webp"),
  "kt_crying": require("../assets/team-characters/kt_crying.webp"),
  "kt_curious": require("../assets/team-characters/kt_curious.webp"),
  "kt_depressed": require("../assets/team-characters/kt_depressed.webp"),
  "kt_flustered": require("../assets/team-characters/kt_flustered.webp"),
  "kt_mocking": require("../assets/team-characters/kt_mocking.webp"),
  "kt_sleepy": require("../assets/team-characters/kt_sleepy.webp"),
  "kt_tongue": require("../assets/team-characters/kt_tongue.webp"),
  "kt_in_love": require("../assets/team-characters/kt_in_love.webp"),
  "kt_extream_shock": require("../assets/team-characters/kt_extream_shock.webp"),
  "kt_devastated": require("../assets/team-characters/kt_devastated.webp"),
  "kt_hot_summer": require("../assets/team-characters/kt_hot_summer.webp"),
  "kt_karen": require("../assets/team-characters/kt_karen.webp"),
  "kt_out": require("../assets/team-characters/kt_out.webp"),
  "kt_praying": require("../assets/team-characters/kt_praying.webp"),
  "kt_rain_cancellation": require("../assets/team-characters/kt_rain_cancellation.webp"),
  "kt_resigned_disgust": require("../assets/team-characters/kt_resigned_disgust.webp"),
  "kt_thumbs_up": require("../assets/team-characters/kt_thumbs_up.webp"),
  "kt_provocative": require("../assets/team-characters/kt_provocative.webp"),
  "lg_default": require("../assets/team-characters/lg_default.webp"),
  "lg_determined": require("../assets/team-characters/lg_determined.webp"),
  "lg_sad": require("../assets/team-characters/lg_sad.webp"),
  "lg_joyful": require("../assets/team-characters/lg_joyful.webp"),
  "lg_neutral": require("../assets/team-characters/lg_neutral.webp"),
  "lg_angry": require("../assets/team-characters/lg_angry.webp"),
  "lg_furious": require("../assets/team-characters/lg_furious.webp"),
  "lg_shocked": require("../assets/team-characters/lg_shocked.webp"),
  "lg_annoyed": require("../assets/team-characters/lg_annoyed.webp"),
  "lg_crying": require("../assets/team-characters/lg_crying.webp"),
  "lg_curious": require("../assets/team-characters/lg_curious.webp"),
  "lg_depressed": require("../assets/team-characters/lg_depressed.webp"),
  "lg_flustered": require("../assets/team-characters/lg_flustered.webp"),
  "lg_mocking": require("../assets/team-characters/lg_mocking.webp"),
  "lg_sleepy": require("../assets/team-characters/lg_sleepy.webp"),
  "lg_tongue": require("../assets/team-characters/lg_tongue.webp"),
  "lg_in_love": require("../assets/team-characters/lg_in_love.webp"),
  "lg_extream_shock": require("../assets/team-characters/lg_extream_shock.webp"),
  "lg_devastated": require("../assets/team-characters/lg_devastated.webp"),
  "lg_hot_summer": require("../assets/team-characters/lg_hot_summer.webp"),
  "lg_karen": require("../assets/team-characters/lg_karen.webp"),
  "lg_out": require("../assets/team-characters/lg_out.webp"),
  "lg_praying": require("../assets/team-characters/lg_praying.webp"),
  "lg_rain_cancellation": require("../assets/team-characters/lg_rain_cancellation.webp"),
  "lg_resigned_disgust": require("../assets/team-characters/lg_resigned_disgust.webp"),
  "lg_thumbs_up": require("../assets/team-characters/lg_thumbs_up.webp"),
  "lg_provocative": require("../assets/team-characters/lg_provocative.webp"),
  "lotte_default": require("../assets/team-characters/lotte_default.webp"),
  "lotte_determined": require("../assets/team-characters/lotte_determined.webp"),
  "lotte_sad": require("../assets/team-characters/lotte_sad.webp"),
  "lotte_joyful": require("../assets/team-characters/lotte_joyful.webp"),
  "lotte_neutral": require("../assets/team-characters/lotte_neutral.webp"),
  "lotte_angry": require("../assets/team-characters/lotte_angry.webp"),
  "lotte_furious": require("../assets/team-characters/lotte_furious.webp"),
  "lotte_shocked": require("../assets/team-characters/lotte_shocked.webp"),
  "lotte_annoyed": require("../assets/team-characters/lotte_annoyed.webp"),
  "lotte_crying": require("../assets/team-characters/lotte_crying.webp"),
  "lotte_curious": require("../assets/team-characters/lotte_curious.webp"),
  "lotte_depressed": require("../assets/team-characters/lotte_depressed.webp"),
  "lotte_flustered": require("../assets/team-characters/lotte_flustered.webp"),
  "lotte_mocking": require("../assets/team-characters/lotte_mocking.webp"),
  "lotte_sleepy": require("../assets/team-characters/lotte_sleepy.webp"),
  "lotte_tongue": require("../assets/team-characters/lotte_tongue.webp"),
  "lotte_in_love": require("../assets/team-characters/lotte_in_love.webp"),
  "lotte_extream_shock": require("../assets/team-characters/lotte_extream_shock.webp"),
  "lotte_devastated": require("../assets/team-characters/lotte_devastated.webp"),
  "lotte_hot_summer": require("../assets/team-characters/lotte_hot_summer.webp"),
  "lotte_karen": require("../assets/team-characters/lotte_karen.webp"),
  "lotte_out": require("../assets/team-characters/lotte_out.webp"),
  "lotte_praying": require("../assets/team-characters/lotte_praying.webp"),
  "lotte_rain_cancellation": require("../assets/team-characters/lotte_rain_cancellation.webp"),
  "lotte_resigned_disgust": require("../assets/team-characters/lotte_resigned_disgust.webp"),
  "lotte_thumbs_up": require("../assets/team-characters/lotte_thumbs_up.webp"),
  "lotte_provocative": require("../assets/team-characters/lotte_provocative.webp"),
  "nc_default": require("../assets/team-characters/nc_default.webp"),
  "nc_determined": require("../assets/team-characters/nc_determined.webp"),
  "nc_sad": require("../assets/team-characters/nc_sad.webp"),
  "nc_joyful": require("../assets/team-characters/nc_joyful.webp"),
  "nc_neutral": require("../assets/team-characters/nc_neutral.webp"),
  "nc_angry": require("../assets/team-characters/nc_angry.webp"),
  "nc_furious": require("../assets/team-characters/nc_furious.webp"),
  "nc_shocked": require("../assets/team-characters/nc_shocked.webp"),
  "nc_annoyed": require("../assets/team-characters/nc_annoyed.webp"),
  "nc_crying": require("../assets/team-characters/nc_crying.webp"),
  "nc_curious": require("../assets/team-characters/nc_curious.webp"),
  "nc_depressed": require("../assets/team-characters/nc_depressed.webp"),
  "nc_flustered": require("../assets/team-characters/nc_flustered.webp"),
  "nc_mocking": require("../assets/team-characters/nc_mocking.webp"),
  "nc_sleepy": require("../assets/team-characters/nc_sleepy.webp"),
  "nc_tongue": require("../assets/team-characters/nc_tongue.webp"),
  "nc_in_love": require("../assets/team-characters/nc_in_love.webp"),
  "nc_extream_shock": require("../assets/team-characters/nc_extream_shock.webp"),
  "nc_devastated": require("../assets/team-characters/nc_devastated.webp"),
  "nc_hot_summer": require("../assets/team-characters/nc_hot_summer.webp"),
  "nc_karen": require("../assets/team-characters/nc_karen.webp"),
  "nc_out": require("../assets/team-characters/nc_out.webp"),
  "nc_praying": require("../assets/team-characters/nc_praying.webp"),
  "nc_rain_cancellation": require("../assets/team-characters/nc_rain_cancellation.webp"),
  "nc_resigned_disgust": require("../assets/team-characters/nc_resigned_disgust.webp"),
  "nc_thumbs_up": require("../assets/team-characters/nc_thumbs_up.webp"),
  "nc_provocative": require("../assets/team-characters/nc_provocative.webp"),
  "samsung_default": require("../assets/team-characters/samsung_default.webp"),
  "samsung_determined": require("../assets/team-characters/samsung_determined.webp"),
  "samsung_sad": require("../assets/team-characters/samsung_sad.webp"),
  "samsung_joyful": require("../assets/team-characters/samsung_joyful.webp"),
  "samsung_neutral": require("../assets/team-characters/samsung_neutral.webp"),
  "samsung_angry": require("../assets/team-characters/samsung_angry.webp"),
  "samsung_furious": require("../assets/team-characters/samsung_furious.webp"),
  "samsung_shocked": require("../assets/team-characters/samsung_shocked.webp"),
  "samsung_annoyed": require("../assets/team-characters/samsung_annoyed.webp"),
  "samsung_crying": require("../assets/team-characters/samsung_crying.webp"),
  "samsung_curious": require("../assets/team-characters/samsung_curious.webp"),
  "samsung_depressed": require("../assets/team-characters/samsung_depressed.webp"),
  "samsung_flustered": require("../assets/team-characters/samsung_flustered.webp"),
  "samsung_mocking": require("../assets/team-characters/samsung_mocking.webp"),
  "samsung_sleepy": require("../assets/team-characters/samsung_sleepy.webp"),
  "samsung_tongue": require("../assets/team-characters/samsung_tongue.webp"),
  "samsung_in_love": require("../assets/team-characters/samsung_in_love.webp"),
  "samsung_extream_shock": require("../assets/team-characters/samsung_extream_shock.webp"),
  "samsung_devastated": require("../assets/team-characters/samsung_devastated.webp"),
  "samsung_hot_summer": require("../assets/team-characters/samsung_hot_summer.webp"),
  "samsung_karen": require("../assets/team-characters/samsung_karen.webp"),
  "samsung_out": require("../assets/team-characters/samsung_out.webp"),
  "samsung_praying": require("../assets/team-characters/samsung_praying.webp"),
  "samsung_rain_cancellation": require("../assets/team-characters/samsung_rain_cancellation.webp"),
  "samsung_resigned_disgust": require("../assets/team-characters/samsung_resigned_disgust.webp"),
  "samsung_thumbs_up": require("../assets/team-characters/samsung_thumbs_up.webp"),
  "samsung_provocative": require("../assets/team-characters/samsung_provocative.webp"),
  "ssg_default": require("../assets/team-characters/ssg_default.webp"),
  "ssg_determined": require("../assets/team-characters/ssg_determined.webp"),
  "ssg_sad": require("../assets/team-characters/ssg_sad.webp"),
  "ssg_joyful": require("../assets/team-characters/ssg_joyful.webp"),
  "ssg_neutral": require("../assets/team-characters/ssg_neutral.webp"),
  "ssg_angry": require("../assets/team-characters/ssg_angry.webp"),
  "ssg_furious": require("../assets/team-characters/ssg_furious.webp"),
  "ssg_shocked": require("../assets/team-characters/ssg_shocked.webp"),
  "ssg_annoyed": require("../assets/team-characters/ssg_annoyed.webp"),
  "ssg_crying": require("../assets/team-characters/ssg_crying.webp"),
  "ssg_curious": require("../assets/team-characters/ssg_curious.webp"),
  "ssg_depressed": require("../assets/team-characters/ssg_depressed.webp"),
  "ssg_flustered": require("../assets/team-characters/ssg_flustered.webp"),
  "ssg_mocking": require("../assets/team-characters/ssg_mocking.webp"),
  "ssg_sleepy": require("../assets/team-characters/ssg_sleepy.webp"),
  "ssg_tongue": require("../assets/team-characters/ssg_tongue.webp"),
  "ssg_in_love": require("../assets/team-characters/ssg_in_love.webp"),
  "ssg_extream_shock": require("../assets/team-characters/ssg_extream_shock.webp"),
  "ssg_devastated": require("../assets/team-characters/ssg_devastated.webp"),
  "ssg_hot_summer": require("../assets/team-characters/ssg_hot_summer.webp"),
  "ssg_karen": require("../assets/team-characters/ssg_karen.webp"),
  "ssg_out": require("../assets/team-characters/ssg_out.webp"),
  "ssg_praying": require("../assets/team-characters/ssg_praying.webp"),
  "ssg_rain_cancellation": require("../assets/team-characters/ssg_rain_cancellation.webp"),
  "ssg_resigned_disgust": require("../assets/team-characters/ssg_resigned_disgust.webp"),
  "ssg_thumbs_up": require("../assets/team-characters/ssg_thumbs_up.webp"),
  "ssg_provocative": require("../assets/team-characters/ssg_provocative.webp"),
};
